#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using AgileWorks_TestToo;
    
    #line 1 "..\..\Views\CustomerSupport\Index.cshtml"
    using AgileWorks_TestToo.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/CustomerSupport/Index.cshtml")]
    public partial class _Views_CustomerSupport_Index_cshtml : System.Web.Mvc.WebViewPage<List<Problem>>
    {
        public _Views_CustomerSupport_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\CustomerSupport\Index.cshtml"
  
    ViewBag.Title = "Home Page";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"jumbotron\"");

WriteLiteral(">\r\n    <p>Add problem to solve:</p>\r\n    <form");

WriteAttribute("action", Tuple.Create(" action=\"", 167), Tuple.Create("\"", 201)
            
            #line 9 "..\..\Views\CustomerSupport\Index.cshtml"
, Tuple.Create(Tuple.Create("", 176), Tuple.Create<System.Object, System.Int32>(Url.Action("AddProblem")
            
            #line default
            #line hidden
, 176), false)
);

WriteLiteral(" method=\"POST\"");

WriteLiteral(">\r\n        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"input-lg col-xs-3\"");

WriteLiteral(" name=\"problem\"");

WriteLiteral(" autofocus required />\r\n        <input");

WriteLiteral(" type=\"datetime-local\"");

WriteLiteral(" class=\"input-lg col-xs-3\"");

WriteLiteral(" id=\"completionTime\"");

WriteLiteral(" name=\"completionTime\"");

WriteLiteral(" min=\"2021-03-24T00:00\"");

WriteLiteral(" required />\r\n        <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-success btn-lg\"");

WriteLiteral(" value=\"Submit\"");

WriteLiteral(">\r\n    </form>\r\n</div>\r\n<h3>");

            
            #line 15 "..\..\Views\CustomerSupport\Index.cshtml"
Write(Model.Count());

            
            #line default
            #line hidden
WriteLiteral(" Problem(s)</h3>\r\n<table");

WriteLiteral(" class=\"table\"");

WriteLiteral(">\r\n    <thead>\r\n        <tr>\r\n            <th>Description</th>\r\n            <th>T" +
"ime issued</th>\r\n            <th>Expected completed</th>\r\n            <th>Is com" +
"pleted</th>\r\n\r\n        </tr>\r\n    </thead>\r\n\r\n    <tbody>\r\n");

            
            #line 28 "..\..\Views\CustomerSupport\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\CustomerSupport\Index.cshtml"
         foreach (var problem in Model)
        {

            
            #line default
            #line hidden
WriteLiteral("        <tr>\r\n            <td>");

            
            #line 31 "..\..\Views\CustomerSupport\Index.cshtml"
           Write(problem.Description);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n            <td>");

            
            #line 32 "..\..\Views\CustomerSupport\Index.cshtml"
           Write(problem.InputTime);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 33 "..\..\Views\CustomerSupport\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\CustomerSupport\Index.cshtml"
             if (problem.CompletionTime.Ticks - DateTime.Now.Ticks < 36000000000)
            {

            
            #line default
            #line hidden
WriteLiteral("                <td>\r\n                <p");

WriteLiteral(" style=\"color:red\"");

WriteLiteral(">");

            
            #line 36 "..\..\Views\CustomerSupport\Index.cshtml"
                                Write(problem.CompletionTime);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                </td>\r\n");

            
            #line 38 "..\..\Views\CustomerSupport\Index.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <td>\r\n");

WriteLiteral("                    ");

            
            #line 42 "..\..\Views\CustomerSupport\Index.cshtml"
               Write(problem.CompletionTime);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n");

            
            #line 44 "..\..\Views\CustomerSupport\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <td>\r\n");

            
            #line 46 "..\..\Views\CustomerSupport\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 46 "..\..\Views\CustomerSupport\Index.cshtml"
                  
                    var url = Url.Action("RemoveProblem", "CustomerSupport", new { issueTime = problem.InputTime });
                
            
            #line default
            #line hidden
WriteLiteral("\r\n                <input");

WriteLiteral(" type=\"checkbox\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 1550), Tuple.Create("\"", 1582)
, Tuple.Create(Tuple.Create("", 1560), Tuple.Create("window.location=\'", 1560), true)
            
            #line 49 "..\..\Views\CustomerSupport\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1577), Tuple.Create<System.Object, System.Int32>(url
            
            #line default
            #line hidden
, 1577), false)
, Tuple.Create(Tuple.Create("", 1581), Tuple.Create("\'", 1581), true)
);

WriteLiteral(" />\r\n            </td>\r\n\r\n        </tr>\r\n");

            
            #line 53 "..\..\Views\CustomerSupport\Index.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral(@"    </tbody>
</table>

<script>
     
    document.getElementById(""completionTime"").onclick = function updateMinTime() {
        var currentTime = new Date();
        var dd = currentTime.getDate();
        var mm = currentTime.getMonth() + 1; //January is 0!
        var yyyy = currentTime.getFullYear();
        var hh = currentTime.getHours();
        var min = currentTime.getMinutes();
        if (dd < 10) {
            dd = '0' + dd
        }
        if (mm < 10) {
            mm = '0' + mm
        }
        if (hh < 10) {
            hh = '0' + hh
        }
        if (min < 10) {
            min = '0' + min
        }
        currentTime = yyyy + '-' + mm + '-' + dd + ""T"" + hh + "":"" + min;
        document.getElementById(""completionTime"").setAttribute(""min"", currentTime);
    }

</script>


");

        }
    }
}
#pragma warning restore 1591
